"""Data models and schemas for Asymmetric Federated Sync with Houston Ground Control.
Defines persistent records for health events, telemetry summaries, model updates,
and federated aggregation state.
"""

from enum import Enum
import datetime
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field


class SyncState(str, Enum):
    """Communication link states between Spacecraft and Houston Ground Control."""
    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
    SYNCING = "SYNCING"


class SyncRecordStatus(str, Enum):
    """Lifecycle status of an individual store-and-forward record."""
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SYNCED = "SYNCED"
    FAILED = "FAILED"


class RecordType(str, Enum):
    """Types of data packets handled by the synchronization queue."""
    HEALTH_EVENT = "HEALTH_EVENT"
    TELEMETRY_SUMMARY = "TELEMETRY_SUMMARY"
    MODEL_UPDATE = "MODEL_UPDATE"


class HealthEventRecord(BaseModel):
    """Clinical anomaly or health event generated onboard during nominal or blackout operations."""
    event_id: str = Field(..., description="Stable unique identifier (e.g. EVT-SPE-9B4F1A)")
    severity: str = Field(..., description="Triage priority: LOW, MEDIUM, HIGH, CRITICAL")
    occurrence_utc: str = Field(..., description="Original onboard timestamp when the clinical event occurred")
    source_pillar: str = Field(..., description="Originating subsystem (P1 Radiation, P2 Voice, P3 Astro-Twin, Centrifuge)")
    title: str = Field(..., description="Clinical title of the health event")
    description: str = Field(..., description="Detailed description of physiological/environmental trigger")
    action_recommended: str = Field(..., description="Autonomous clinical action prescribed onboard")
    risk_score: float = Field(default=0.1, description="Fused risk score at time of event [0.0 - 1.0]")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Structured clinical parameters")
    telemetry_checksum_sha256: str = Field(..., description="Cryptographic SHA-256 integrity hash")
    idempotency_key: str = Field(..., description="Key preventing duplicate ingestion on retries")
    sync_status: SyncRecordStatus = Field(default=SyncRecordStatus.PENDING)
    ground_received_utc: Optional[str] = Field(default=None, description="Actual timestamp when Houston downlinked and processed the event")
    attempts: int = Field(default=0, description="Number of upload attempts")
    last_error: Optional[str] = Field(default=None, description="Error message if sync failed")
    explanation: Optional[Dict[str, Any]] = Field(default=None, description="SHAP explainability package (Feature B)")



class TelemetrySummaryRecord(BaseModel):
    """Periodic compressed telemetry rollup for baseline mission tracking."""
    summary_id: str = Field(..., description="Unique summary packet ID")
    timestamp_utc: str = Field(..., description="Timestamp of snapshot creation")
    scenario_id: str = Field(default="normal")
    risk_level: str = Field(default="LOW")
    risk_score: float = Field(default=0.10)
    dose_rate_msv_h: float = Field(default=0.02)
    voice_strain: float = Field(default=0.12)
    projected_bone_loss: float = Field(default=0.8)
    telemetry_checksum_sha256: str = Field(..., description="SHA-256 payload checksum")
    sync_status: SyncRecordStatus = Field(default=SyncRecordStatus.PENDING)
    ground_received_utc: Optional[str] = Field(default=None)
    attempts: int = Field(default=0)
    last_error: Optional[str] = Field(default=None)


class ModelUpdateRecord(BaseModel):
    """Federated learning local model parameter update generated by an edge client."""
    update_id: str = Field(..., description="Unique update identifier (e.g. UPD-FL-HERMES-01-R1)")
    client_id: str = Field(..., description="Edge client node identifier (e.g. HERMES-EDGE-01)")
    base_version: str = Field(..., description="Global model version this update was trained against (e.g. v1.0.0)")
    timestamp_utc: str = Field(..., description="Time local training completed")
    num_samples: int = Field(..., description="Local training sample count (weighting factor for FedAvg)")
    loss: float = Field(..., description="Local convergence loss")
    weights_delta: Dict[str, float] = Field(..., description="Model parameter deltas: delta_W = W_local - W_global")
    weights_checksum_sha256: str = Field(..., description="SHA-256 hash of the weight deltas")
    sync_status: SyncRecordStatus = Field(default=SyncRecordStatus.PENDING)
    ground_received_utc: Optional[str] = Field(default=None)
    aggregated: bool = Field(default=False, description="Whether this update was aggregated into the global model")
    attempts: int = Field(default=0)
    last_error: Optional[str] = Field(default=None)


class FederatedGlobalModel(BaseModel):
    """Aggregated global model maintained by Houston Ground Control."""
    version: str = Field(..., description="Semantic global model version (e.g. v1.1.0)")
    round: int = Field(default=1, description="Federated aggregation round number")
    base_version: str = Field(default="v1.0.0")
    aggregated_at_utc: str = Field(...)
    num_participating_clients: int = Field(default=1)
    total_samples_trained: int = Field(default=0)
    global_weights: Dict[str, float] = Field(default_factory=dict)
    weights_checksum_sha256: str = Field(...)
    aggregation_notes: str = Field(default="Initial baseline model")


class SyncActivityLog(BaseModel):
    """Audit log entry for communication transitions and synchronization operations."""
    log_id: str = Field(...)
    timestamp_utc: str = Field(...)
    action: str = Field(..., description="Action name: STATE_CHANGE, EVENT_ENQUEUED, SYNC_BATCH, AGGREGATION, RETRY")
    status: str = Field(..., description="SUCCESS, WARNING, ERROR, INFO")
    details: str = Field(...)


class SyncStatusOverview(BaseModel):
    """Unified telemetry overview of the Deep Space Communications & Federated Sync subsystem."""
    comms_state: SyncState
    pending_health_events: int
    pending_telemetry_summaries: int
    pending_model_updates: int
    synced_records_total: int
    failed_records_total: int
    unsynchronized_critical_count: int
    last_successful_sync_utc: Optional[str] = None
    local_model_version: str
    ground_model_version: str
    simulated_latency_seconds: int = 1200  # Default 20 minutes (1200 seconds)
    simulated_failure_rate_pct: float = 0.0
